<div class="panel panel-default spacer">
    <div class="panel-heading"><h4>Shortened Link</h4></div>
    <div class="panel-body">

        <table class="table">
            <tr>
                <th>Name</th>
                <th>Short Url</th>
                <th>QR Code</th>
            </tr>
            <tr>
                <td><?= $link->getName() ?></td>
                <td><a href=" <?= $link->getLongUrl() ?>"><?= $link->getShortUrl() ?></a></td>
                <td><img src="/img/qr_code.png" alt="This Image does not exist"></td>
            </tr>
        </table>
    </div>
</div>
